# Site settings
title: 七三工作室
email: qisanstudio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.qisanstudio.com" # the base hostname & protocol for your site
twitter_username: qisanstudio
github_username:  qisanstudio

# Build settings
markdown: kramdown
